# name: assignments_test
# on: [push, pull_request]
# jobs:
#   run_assignments:
#     runs-on: ubuntu-latest
#     if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

#     steps:
#       - name: Checkout the repository
#         uses: actions/checkout@v3

#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'zulu'
#           java-version: 17

#       - name: Setup python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.8

#       - name: Clone cse1110/assignments
#         uses: actions/checkout@v3
#         with:
#           repository: 'cse1110/assignments'
#           path: 'assignments'

#       - name: Compile Andy
#         run: |
#           mvn -f andy/pom.xml clean package -Djar.finalName=andy -Dmaven.test.skip && mv andy/target/andy.jar /home/runner/work/andy/

#       - name: Execute python script
#         run: |
#           python ./.github/scripts/assignments_test.py
