name: tests_docker
on: push
jobs:
  run_tests_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Clone cse1110/weblab-docker-v2
        uses: actions/checkout@v3
        with:
          repository: 'cse1110/weblab-docker-v2'
          path: 'weblab-docker-v2'
          ssh-key: ${{ secrets.DOCKER_REPO_DEPLOY_KEY }}
          persist-credentials: false

      - name: Configure Dockerfile
        working-directory: ./weblab-docker-v2
        run: |
          sed -i -E 's|git clone .+|git clone -n ${{ github.server_url }}/${{ github.repository }}.git|; s|RUN mvn clean package.*|RUN git checkout ${{ github.sha }}\nRUN mvn test|; s|RUN mv .+||' Dockerfile

      - name: Run tests in Docker
        working-directory: ./weblab-docker-v2
        run: |
          make
